// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadFileOpen returns the embedded CollectionSpec for FileOpen.
func LoadFileOpen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileOpenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FileOpen: %w", err)
	}

	return spec, err
}

// LoadFileOpenObjects loads FileOpen and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FileOpenObjects
//	*FileOpenPrograms
//	*FileOpenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFileOpenObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFileOpen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FileOpenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileOpenSpecs struct {
	FileOpenProgramSpecs
	FileOpenMapSpecs
	FileOpenVariableSpecs
}

// FileOpenProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileOpenProgramSpecs struct {
	TraceFileOpen *ebpf.ProgramSpec `ebpf:"trace_file_open"`
}

// FileOpenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileOpenMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// FileOpenVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileOpenVariableSpecs struct {
}

// FileOpenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileOpenObjects struct {
	FileOpenPrograms
	FileOpenMaps
	FileOpenVariables
}

func (o *FileOpenObjects) Close() error {
	return _FileOpenClose(
		&o.FileOpenPrograms,
		&o.FileOpenMaps,
	)
}

// FileOpenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileOpenMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *FileOpenMaps) Close() error {
	return _FileOpenClose(
		m.Events,
	)
}

// FileOpenVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileOpenVariables struct {
}

// FileOpenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFileOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileOpenPrograms struct {
	TraceFileOpen *ebpf.Program `ebpf:"trace_file_open"`
}

func (p *FileOpenPrograms) Close() error {
	return _FileOpenClose(
		p.TraceFileOpen,
	)
}

func _FileOpenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fileopen_arm64_bpfel.o
var _FileOpenBytes []byte
