// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

// This file mirrors the bpf2go output shape for the mount probe so the daemon
// compiles on the host (darwin/arm64) before the real object is generated.
// The embedded .o is a placeholder until `go generate ./...` is run INSIDE the
// Lima VM (clang -target bpf + vmlinux.h exist only there); regeneration
// overwrites both this file and mount_arm64_bpfel.o with the compiled program.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadMount returns the embedded CollectionSpec for Mount.
func LoadMount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Mount: %w", err)
	}

	return spec, err
}

// LoadMountObjects loads Mount and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MountObjects
//	*MountPrograms
//	*MountMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMountObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MountSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MountSpecs struct {
	MountProgramSpecs
	MountMapSpecs
	MountVariableSpecs
}

// MountProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MountProgramSpecs struct {
	TraceMount *ebpf.ProgramSpec `ebpf:"trace_mount"`
}

// MountMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MountMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	VrTargetCgroup *ebpf.MapSpec `ebpf:"vr_target_cgroup"`
}

// MountVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MountVariableSpecs struct {
}

// MountObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type MountObjects struct {
	MountPrograms
	MountMaps
	MountVariables
}

func (o *MountObjects) Close() error {
	return _MountClose(
		&o.MountPrograms,
		&o.MountMaps,
	)
}

// MountMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type MountMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	VrTargetCgroup *ebpf.Map `ebpf:"vr_target_cgroup"`
}

func (m *MountMaps) Close() error {
	return _MountClose(
		m.Events,
		m.VrTargetCgroup,
	)
}

// MountVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type MountVariables struct {
}

// MountPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type MountPrograms struct {
	TraceMount *ebpf.Program `ebpf:"trace_mount"`
}

func (p *MountPrograms) Close() error {
	return _MountClose(
		p.TraceMount,
	)
}

func _MountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mount_arm64_bpfel.o
var _MountBytes []byte
