// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadProcessExit returns the embedded CollectionSpec for ProcessExit.
func LoadProcessExit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessExitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ProcessExit: %w", err)
	}

	return spec, err
}

// LoadProcessExitObjects loads ProcessExit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcessExitObjects
//	*ProcessExitPrograms
//	*ProcessExitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcessExitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProcessExit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcessExitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessExitSpecs struct {
	ProcessExitProgramSpecs
	ProcessExitMapSpecs
	ProcessExitVariableSpecs
}

// ProcessExitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessExitProgramSpecs struct {
	TraceExit *ebpf.ProgramSpec `ebpf:"trace_exit"`
}

// ProcessExitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessExitMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ProcessExitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessExitVariableSpecs struct {
}

// ProcessExitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcessExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessExitObjects struct {
	ProcessExitPrograms
	ProcessExitMaps
	ProcessExitVariables
}

func (o *ProcessExitObjects) Close() error {
	return _ProcessExitClose(
		&o.ProcessExitPrograms,
		&o.ProcessExitMaps,
	)
}

// ProcessExitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcessExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessExitMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ProcessExitMaps) Close() error {
	return _ProcessExitClose(
		m.Events,
	)
}

// ProcessExitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProcessExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessExitVariables struct {
}

// ProcessExitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcessExitObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessExitPrograms struct {
	TraceExit *ebpf.Program `ebpf:"trace_exit"`
}

func (p *ProcessExitPrograms) Close() error {
	return _ProcessExitClose(
		p.TraceExit,
	)
}

func _ProcessExitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processexit_arm64_bpfel.o
var _ProcessExitBytes []byte
