// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadProcessExec returns the embedded CollectionSpec for ProcessExec.
func LoadProcessExec() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessExecBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ProcessExec: %w", err)
	}

	return spec, err
}

// LoadProcessExecObjects loads ProcessExec and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcessExecObjects
//	*ProcessExecPrograms
//	*ProcessExecMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcessExecObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProcessExec()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcessExecSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessExecSpecs struct {
	ProcessExecProgramSpecs
	ProcessExecMapSpecs
	ProcessExecVariableSpecs
}

// ProcessExecProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessExecProgramSpecs struct {
	TraceExec *ebpf.ProgramSpec `ebpf:"trace_exec"`
}

// ProcessExecMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessExecMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ProcessExecVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessExecVariableSpecs struct {
}

// ProcessExecObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessExecObjects struct {
	ProcessExecPrograms
	ProcessExecMaps
	ProcessExecVariables
}

func (o *ProcessExecObjects) Close() error {
	return _ProcessExecClose(
		&o.ProcessExecPrograms,
		&o.ProcessExecMaps,
	)
}

// ProcessExecMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessExecMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ProcessExecMaps) Close() error {
	return _ProcessExecClose(
		m.Events,
	)
}

// ProcessExecVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessExecVariables struct {
}

// ProcessExecPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcessExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessExecPrograms struct {
	TraceExec *ebpf.Program `ebpf:"trace_exec"`
}

func (p *ProcessExecPrograms) Close() error {
	return _ProcessExecClose(
		p.TraceExec,
	)
}

func _ProcessExecClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processexec_arm64_bpfel.o
var _ProcessExecBytes []byte
